services:
  postgres:
    image: postgres:15-alpine
    container_name: booking_postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: Booking_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d Booking_db"]
      interval: 5s
      timeout: 3s
      retries: 12

  redis:
    image: redis:7-alpine
    container_name: booking_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12

  mongo:
    image: mongo:7
    container_name: booking_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok'"]
      interval: 5s
      timeout: 3s
      retries: 12

  api:
    build:
      context: ./BookingSystem.API
      dockerfile: BookingSystem.API/Dockerfile
    container_name: booking_api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=Booking_db;Username=my_user;Password=1111"
      ConnectionStrings__Redis: "redis:6379"
      MongoDbConnection: "mongodb://admin:password123@mongo:27017"
    ports:
      - "5044:8080"

volumes:
  pg_data:
